# Generated by Django 5.2.6 on 2026-07-11 22:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_auto_add_new_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='submission',
            new_name='forms_submi_form_id_ff9261_idx',
            old_name='forms_submi_form_status_idx',
        ),
        migrations.RenameIndex(
            model_name='submission',
            new_name='forms_submi_submitt_6d0094_idx',
            old_name='forms_submi_submitter_idx',
        ),
        migrations.AddField(
            model_name='submission',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='field',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('dropdown', 'Dropdown'), ('checkbox', 'Checkbox'), ('file', 'File Upload'), ('email', 'Email'), ('textarea', 'Text Area')], max_length=50),
        ),
        migrations.AlterField(
            model_name='form',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to=settings.AUTH_USER_MODEL),
        ),
    ]
