# Generated by Django 5.2.6 on 2026-07-13 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_rename_forms_submi_form_status_idx_forms_submi_form_id_ff9261_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='due_date',
            field=models.DateField(blank=True, db_index=True, help_text='Deadline for completing this submission', null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='escalation_level',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Friendly Reminder'), (2, 'Urgent Warning'), (3, 'Penalty Applied'), (4, 'Final Notice')], db_index=True, default=0, help_text='Current escalation stage (0=none, 1=reminder, 2=urgent, 3=penalty, 4=final)'),
        ),
        migrations.AddField(
            model_name='submission',
            name='last_reminder_sent_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last escalation notification sent', null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='penalty_applied_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when penalty was applied', null=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('email', 'Email'), ('phone', 'Phone'), ('number', 'Number'), ('currency', 'Currency'), ('date', 'Date'), ('textarea', 'Text Area'), ('dropdown', 'Dropdown'), ('checkbox', 'Checkbox'), ('file', 'File Upload')], max_length=50),
        ),
    ]
